// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6jODS73PpJxuy0sl8Cfg2BKGwJ1mz4_0',
    appId: '1:695236528926:web:fec1afd3ebc771aafb970f',
    messagingSenderId: '695236528926',
    projectId: 'thoughtful-thinking-coach-new',
    authDomain: 'thoughtful-thinking-coach-new.firebaseapp.com',
    storageBucket: 'thoughtful-thinking-coach-new.appspot.com',
    measurementId: 'G-CSS72SFTTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZh6DtC3JNsxscK5CKhJpgjxOElw-vVY',
    appId: '1:695236528926:android:1cc3a91b6d88667ffb970f',
    messagingSenderId: '695236528926',
    projectId: 'thoughtful-thinking-coach-new',
    storageBucket: 'thoughtful-thinking-coach-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9L2y86i9UTQ5r44s243KVP6uO-pFzzUo',
    appId: '1:695236528926:ios:961ea9faae83af21fb970f',
    messagingSenderId: '695236528926',
    projectId: 'thoughtful-thinking-coach-new',
    storageBucket: 'thoughtful-thinking-coach-new.appspot.com',
    iosBundleId: 'com.example.thoughtfulThinkingCoachNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9L2y86i9UTQ5r44s243KVP6uO-pFzzUo',
    appId: '1:695236528926:ios:3be5c17336216f14fb970f',
    messagingSenderId: '695236528926',
    projectId: 'thoughtful-thinking-coach-new',
    storageBucket: 'thoughtful-thinking-coach-new.appspot.com',
    iosBundleId: 'com.example.thoughtfulThinkingCoachNew.RunnerTests',
  );
}
